// Generated by golden_board.checks from spec/constants-v0.json.
// Source SHA-256: 76e6ffd2478e569a7bd00210d27d4cbf958ad034b21346746282dd7aa2395d3b
// Do not edit by hand.

pub const IDENTITY_TEST_A: &[u8] = b"GB-IDENTITY-TEST-A-v0\0";
pub const IDENTITY_TEST_B: &[u8] = b"GB-IDENTITY-TEST-B-v0\0";
pub const MANIFEST: &[u8] = b"GB-MANIFEST-v0\0";

pub const MANIFEST_DIAGNOSTICS: &[&str] = &[
    "manifest.limit",
    "manifest.utf8",
    "manifest.syntax",
    "manifest.trailing_data",
    "manifest.duplicate_key",
    "manifest.unsupported_type",
    "manifest.integer_range",
    "manifest.invalid_key",
    "manifest.invalid_unicode",
    "manifest.noncanonical",
];
