# Generated by golden_board.checks from spec/constants-v0.json.
# Source SHA-256: 76e6ffd2478e569a7bd00210d27d4cbf958ad034b21346746282dd7aa2395d3b
# Do not edit by hand.

IDENTITY_TEST_A = b'GB-IDENTITY-TEST-A-v0\x00'
IDENTITY_TEST_B = b'GB-IDENTITY-TEST-B-v0\x00'
MANIFEST = b'GB-MANIFEST-v0\x00'

MANIFEST_DIAGNOSTICS = (
    'manifest.limit',
    'manifest.utf8',
    'manifest.syntax',
    'manifest.trailing_data',
    'manifest.duplicate_key',
    'manifest.unsupported_type',
    'manifest.integer_range',
    'manifest.invalid_key',
    'manifest.invalid_unicode',
    'manifest.noncanonical',
)
